var myName;
myName = "Sagar Matkar";
console.log("My First & Last Name:", myName);
var myFullName;
myFullName = "Sagar Parmeshwar Matkar";
console.log("My Full Name:", myFullName);
var myLove = "I love only JS"; 
console.log("", myLove);
var firstName = "Sagar"; 
console.log("First Name:", firstName);
var lastName = "Matkar"; 
console.log("Last Name:", lastName);
var age = "22"; 
console.log("Age:", age);
var address = "Pune"; 
console.log("Address:", address);
var pinCode = "411047"; 
console.log("Pin Code:", pinCode);
var gender = "Male"; 
console.log("Gender:", gender);
var isMarried = "Unmarried"; 
console.log("Is Married:", isMarried);